### PR TITLE
McGraw-Hill Medical

### PR DESCRIPTION
**Pull request by AGCooper**
What started out as a parser for AccessSurgery has become a parser for McGraw-Hill Medical at large. This is my first pull request and any feedback will be much appreciated. See also:

http://ang.couperin.org/platforms/546616edbae67e3c20493b58

https://trello.com/c/UIcaR0QT/154-mcgraw-hill-medical-mhm

### CODE REVIEW

**Comment by AGCooper** [comment]
I forgot to delete the backup copy of the parser I made so that's part of the commit.

**Comment by tporquet** [comment]
Hello Lisa, Elisabeth, Alex,

Thank you for all this work!
We would like to merge your pull request soon. Is it now in a state where we can do it?

If you want to add more parsers, our advice is that you issue one pull request per parser: it is easier for us to review the code at that level of granularity.

What should we do with the PULL_REQUEST_TEMPLATE.md file? Is seems to be an internal documentation on your end, is it correct?

Best,
Thomas for the ezTeam

**Comment by AGCooper** [comment]
Hi Thomas,

Thank you very much for this note. And yeah this pull request has gotten rather messy. I was thinking about how to avoid piling multiple platforms into one pull request. And yes that .md file is local also. 

Let me look into cleaning this up and developing a better approach on our end. I will probably close this pull request and send another for MHM only.

Best,

Alex

**Comment by AGCooper** [comment]
Closing this pull request to submit a new one.

**Comment by AGCooper** [comment]
Hi Thomas,

I have closed the previous pull request and replaced it with a request for
MHM only. https://github.com/ezpaarse-project/ezpaarse-platforms/pull/90
This is ready to be merged.

Going forward we will try to limit one pull request to one platform.

Thank you,

Alex

**Pull request closed without merging**
